import { BsArrowRightCircleFill } from "react-icons/bs";
import { IoSearchOutline } from "react-icons/io5";
import { BsCart3 } from "react-icons/bs";
import { IoMdNotificationsOutline } from "react-icons/io";
import { FaRegCircleUser } from "react-icons/fa6";
import { IoSettingsOutline } from "react-icons/io5";
import { MdLogout } from "react-icons/md";
import { FaBookReader } from "react-icons/fa";
import { MdOutlinePublish } from "react-icons/md";
import { MdPeopleAlt } from "react-icons/md";
import { PiStarFourFill } from "react-icons/pi";
import { FaTiktok } from "react-icons/fa";
import { TiSocialFacebookCircular } from "react-icons/ti";
import { FaInstagram } from "react-icons/fa6";
import { FaYoutube } from "react-icons/fa";
import { GoHomeFill } from "react-icons/go";
import { PiBookBookmarkFill } from "react-icons/pi";
import { FaMoneyBillTransfer } from "react-icons/fa6";
import { LuBookUp } from "react-icons/lu";
import { IoIosMore } from "react-icons/io";
import { GiSpellBook } from "react-icons/gi";
import { MdFormatListBulletedAdd } from "react-icons/md";
import { LuArrowLeft } from "react-icons/lu";
import { IoMdHeartEmpty } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoIosArrowDropleft } from "react-icons/io";
import { IoIosArrowDropright } from "react-icons/io";
import { BsReverseLayoutTextWindowReverse } from "react-icons/bs";
import { CgDanger } from "react-icons/cg";
import { FaImage } from "react-icons/fa6";
import { HiMiniArrowUpTray } from "react-icons/hi2";
import { BsStars } from "react-icons/bs";
import { GoGraph } from "react-icons/go";
import { FaUsers } from "react-icons/fa6";
import { ImBooks } from "react-icons/im";
import { ImUserPlus } from "react-icons/im";
import { RiMoneyDollarCircleFill } from "react-icons/ri";
import { TbPigMoney } from "react-icons/tb";
import { RiExpandDiagonalLine } from "react-icons/ri";
import { IoColorWandSharp } from "react-icons/io5";
import { BiMoneyWithdraw } from "react-icons/bi";
import { BsGraphUpArrow } from "react-icons/bs";

export const Profits = BsGraphUpArrow;
export const SalesTotal = BiMoneyWithdraw;
export const Cerdo = TbPigMoney;
export const Pen = IoColorWandSharp;
export const Expant = RiExpandDiagonalLine;
export const Search = IoSearchOutline;
export const Flechita = BsArrowRightCircleFill;
export const Shopping = BsCart3;
export const Notification = IoMdNotificationsOutline;
export const User = FaRegCircleUser;
export const Setting = IoSettingsOutline;
export const Exit = MdLogout;
export const Publish = MdOutlinePublish;
export const People = MdPeopleAlt;
export const Start = PiStarFourFill;
export const Tiktok = FaTiktok;
export const Facebook = TiSocialFacebookCircular;
export const Ig = FaInstagram;
export const Youtube = FaYoutube;
export const Home = GoHomeFill;
export const Read = FaBookReader;
export const Book = PiBookBookmarkFill;
export const Money = FaMoneyBillTransfer;
export const Moneydos = RiMoneyDollarCircleFill;
export const Books = LuBookUp;
export const More = IoIosMore;
export const ReadBook = GiSpellBook;
export const List = MdFormatListBulletedAdd;
export const FlechaRegresar = LuArrowLeft;
export const IconoloveVacio = IoMdHeartEmpty;
export const Iconolovelleno = FaHeart;
export const Flechaleft = IoIosArrowDropleft;
export const Flecharight = IoIosArrowDropright;
export const Window = BsReverseLayoutTextWindowReverse;
export const Danger = CgDanger;
export const Image = FaImage;
export const Up = HiMiniArrowUpTray;
export const Destello = BsStars;
export const Grafi = GoGraph;
export const USers = FaUsers;
export const Bookss = ImBooks;
export const NewUser = ImUserPlus;